---
name: Create the bundle

on:
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      # --------------------------------------
      # --------- | Prerequisites | ----------
      # --------------------------------------

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      # --------------------------------------
      # ------- | Install compilers | --------
      # --------------------------------------

      - name: Install the dotnet compilers
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.5'
      
      # --------------------------------------
      # ------- | Compile the tools | --------
      # --------------------------------------

      - name: Compile Seatbelt
        run: dotnet build -c Release
        working-directory: ./toolbox/windows/enum/seatbelt
      
      - name: Copy the Seatbelt binary
        run: find ./toolbox/windows/enum/seatbelt

      # ---------------------------------------
      # ------ | Bundle all the tools | -------
      # ---------------------------------------

      - name: Linux > Pivoting > NetCat
        run: |
          mkdir -p ./_bundle/linux/pivoting/netcat
          mv ./toolbox/linux/pivoting/nmap-binaries/nmap/linux/x86-64/ncat                        ./_bundle/linux/pivoting/ncat/ncat64

      - name: Linux > Pivoting > Nmap
        run: |
          mkdir -p ./_bundle/linux/pivoting/nmap
          mv ./toolbox/linux/pivoting/nmap-binaries/nmap/linux/x86-64/nmap                        ./_bundle/linux/pivoting/nmap/nmap64
          mv ./toolbox/linux/pivoting/nmap-binaries/nmap/linux/x86-64/nping                       ./_bundle/linux/pivoting/nmap/nping64

      - name: Phishing > Office365
        run: |
          mkdir -p ./_bundle/phishing/templates/office365
          mv ./toolbox/phishing/zeropointsecurity-office365/Office365/*.html                       ./_bundle/phishing/templates/office365/

      - name: Windows > Bypass > Invisi-Shell
        run: |
          mkdir -p ./_bundle/windows/bypass/invisi-shell
          mv ./toolbox/windows/bypass/invisi-shell/build/x64/Release/InvisiShellProfiler.dll      ./_bundle/windows/bypass/invisi-shell/
          mv ./toolbox/windows/bypass/invisi-shell/RunWithPathAsAdmin.bat                         ./_bundle/windows/bypass/invisi-shell/
          mv ./toolbox/windows/bypass/invisi-shell/RunWithRegistryNonAdmin.bat                    ./_bundle/windows/bypass/invisi-shell/

      - name: Windows > Pivoting > NetCat
        run: |
          mkdir -p ./_bundle/windows/pivoting/netcat
          mv ./toolbox/windows/pivoting/netcat-binaries/nc.exe                                    ./_bundle/windows/pivoting/netcat/
          mv ./toolbox/windows/pivoting/netcat-binaries/nc64.exe                                  ./_bundle/windows/pivoting/netcat/
          mv ./toolbox/windows/pivoting/powercat/powercat.ps1                                     ./_bundle/windows/pivoting/netcat/

      - name: Windows > Pivoting > PSRemoting
        run: |
          mkdir -p ./_bundle/windows/pivoting/psremoting
          mv ./toolbox/windows/pivoting/_archive/samratashok/Find-PSRemotingLocalAdminAccess.ps1  ./_bundle/windows/pivoting/psremoting/

      - name: Windows > PrivEsc > PowerUp
        run: |
          mkdir -p ./_bundle/windows/privesc/powerup
          mv ./toolbox/windows/enum/powersploit/Privesc/PowerUp.ps1                               ./_bundle/windows/privesc/powerup/
      
      - name: Windows > Recon > ADModule
        run: |
          mkdir -p ./_bundle/windows/recon/admodule
          mv ./toolbox/windows/enum/admodule/Microsoft.ActiveDirectory.Management.dll             ./_bundle/windows/recon/admodule/
          mv ./toolbox/windows/enum/admodule/ActiveDirectory/ActiveDirectory.psd1                 ./_bundle/windows/recon/admodule/
          mv ./toolbox/windows/enum/admodule/Import-ActiveDirectory.ps1                           ./_bundle/windows/recon/admodule/

      - name: Windows > Recon > PowerView
        run: |
          mkdir -p ./_bundle/windows/recon/mailsniper
          mv ./toolbox/windows/enum/mailsniper/MailSniper.ps1                                     ./_bundle/windows/recon/mailsniper/

      - name: Windows > Recon > PowerView
        run: |
          mkdir -p ./_bundle/windows/recon/powerview
          mv ./toolbox/windows/enum/powersploit/Recon/PowerView.ps1                               ./_bundle/windows/recon/powerview/

      - name: Windows > Utils > PowerView
        run: |
          mkdir -p ./_bundle/windows/utils/usernamepermutation
          mv ./toolbox/windows/utils/_custom/Username-Permutation.ps1                             ./_bundle/windows/utils/usernamepermutation/

      # ---------------------------------------
      # ------- | Compress the bundle | -------
      # ---------------------------------------

      - name: Upload the compressed archive to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: toolbox
          path: ./_bundle/
          compression-level: 9
          if-no-files-found: error
