---
name: Create the bundle

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      # ---------------------------------------
      # ---------- | Prerequisites | ----------
      # ---------------------------------------

      - name: Checkout the repository
        uses: actions/checkout@v4
      
      - name: Setup DotNet
        uses: actions/setup-dotnet@v4

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      


      # ---------------------------------------
      # --- | Create the bundle directory | ---
      # ---------------------------------------

      - name: Create a new bundle directory
        run: mkdir -p ./_bundle/

      # --- | Tools | ---

      - name: Windows > Bypass > Invisi-Shell
        run: |
          mkdir -p ./_bundle/windows/bypass/invisi-shell
          mv ./toolbox/windows/bypass/invisi-shell/build/x64/Release/InvisiShellProfiler.dll      ./_bundle/windows/bypass/invisi-shell/
          mv ./toolbox/windows/bypass/invisi-shell/RunWithPathAsAdmin.bat                         ./_bundle/windows/bypass/invisi-shell/
          mv ./toolbox/windows/bypass/invisi-shell/RunWithRegistryNonAdmin.bat                    ./_bundle/windows/bypass/invisi-shell/

      - name: Windows > Pivoting > NetCat
        run: |
          find .
          mkdir -p ./_bundle/windows/pivoting/netcat
          mv ./toolbox/windows/pivoting/netcat-binaries/nc.exe                                    ./_bundle/windows/pivoting/netcat/
          mv ./toolbox/windows/pivoting/netcat-binaries/nc64.exe                                  ./_bundle/windows/pivoting/netcat/
          mv ./toolbox/windows/pivoting/powercat/powercat.ps1                                     ./_bundle/windows/pivoting/netcat/

      - name: Windows > Pivoting > PSRemoting
        run: |
          mkdir -p ./_bundle/windows/pivoting/psremoting
          mv ./toolbox/windows/pivoting/_archive/samratashok/Find-PSRemotingLocalAdminAccess.ps1  ./_bundle/windows/pivoting/psremoting/

      - name: Windows > Post > SafetyKatz
        run: |
          mkdir -p ./_bundle/windows/post/safetykatz
          cd ./toolbox/windows/post/safetykatz
          dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true
          mv ./bin/Release/net5.0/win-x64/publish/SafetyKatz.exe                                   ../../../../../_bundle/windows/post/safetykatz/

      - name: Windows > PrivEsc > PowerUp
        run: |
          mkdir -p ./_bundle/windows/privesc/powerup
          mv ./toolbox/windows/enum/powersploit/Privesc/PowerUp.ps1                               ./_bundle/windows/privesc/powerup/
      
      - name: Windows > Recon > ADModule
        run: |
          mkdir -p ./_bundle/windows/recon/admodule
          mv ./toolbox/windows/enum/admodule/Microsoft.ActiveDirectory.Management.dll             ./_bundle/windows/recon/admodule/
          mv ./toolbox/windows/enum/admodule/ActiveDirectory/ActiveDirectory.psd1                 ./_bundle/windows/recon/admodule/
          mv ./toolbox/windows/enum/admodule/Import-ActiveDirectory.ps1                           ./_bundle/windows/recon/admodule/

      - name: Windows > Recon > PowerView
        run: |
          mkdir -p ./_bundle/windows/recon/powerview
          mv ./toolbox/windows/enum/powersploit/Recon/PowerView.ps1                               ./_bundle/windows/recon/powerview/


      # --- | Bundle | ---

      - name: Upload the compressed archive to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: toolbox
          path: ./_bundle/
          compression-level: 9
          if-no-files-found: error