---
name: Compile the binaries

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 */30 * *'

jobs:
  compile-dotnet:
    runs-on: windows-latest

    steps:
      # --------------------------------------
      # --------- | Prerequisites | ----------
      # --------------------------------------

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '5.0.x'
      
      # --------------------------------------
      # ------- | Compile the tools | --------
      # --------------------------------------

      - name: Windows > Seatbelt :: Target .NET 5.0
        working-directory: ./toolbox/windows/enum/seatbelt/Seatbelt
        run: |
          (Get-Content 'Seatbelt.csproj') -replace '<TargetFramework>.*</TargetFramework>', '<TargetFramework>net5.0</TargetFramework>' | Set-Content 'Seatbelt.csproj'

      - name: Windows > Seatbelt :: Compilation
        working-directory: ./toolbox/windows/enum/seatbelt
        run: dotnet build -c Release
    
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            **/bin/Release/*

